starting mobile version from 0
latinogan/mobile-version pull request #1
Opened 2022-02-16 17:51 UTC by latinogan

2022-02-16 21:03 UTC, Whoistolu requested changes
Hi @latinogan,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

#### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 21:03 UTC, Whoistolu commented on index.html
> +<body>
- [ ] [REQUIRED] Please check the width of the body as you have horizontal scroll bars. kindly ensure your design looks more like the provided design in the template you have chosen.
![Screenshot from 2022-02-16 21-52-45](https://user-images.githubusercontent.com/58692590/154356303-c1fbcb00-336f-48dd-ac37-aed2fc3ec0f3.png)
![Screenshot from 2022-02-16 21-52-51](https://user-images.githubusercontent.com/58692590/154356320-f1cf1c3e-d4e8-472c-81da-de2eff60e156.png)

2022-02-17 17:32 UTC, medaminedev66 requested changes
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] Kindly add a pull request description of what you have done in this pull request so that others can read what is being worked on.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 17:32 UTC, medaminedev66 commented on csssss
> +  font-size: 17px;
- [ ] Kindly remove the unused `csssss` file so your repository is clean.

2022-02-17 17:32 UTC, medaminedev66 commented on index.html
>      <header>
- [ ] Kindly remove the gap from the top and the left of your page to improve your UI design.
- [ ] Please also as required in the project requirements, you must stick to the design as much as possible (margins top, bottom, right, and left, font and font sizes) using the Figma Template provided. I would recommend using the same fonts that are provided in the Figma design.
<img width="214" alt="image" src="https://user-images.githubusercontent.com/77190203/154537390-dfa2165a-2d6f-4542-92c7-94c2fa5994ab.png">

2022-02-17 17:38 UTC, latinogan commented on csssss
> +  font-size: 17px;
ohh sorry about that i though i deleted before send the pull request

2022-02-17 20:20 UTC, JuliCarracedo approved these changes
Hi @latinogan , 
    
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
    Congratulations! 🎉 

### Acknowledgement 
You did a great job so far! I'm aware you are just starting Microverse, so I won't demoralize you by rejecting your project. But there's still a ton of room for improvement. Portfolios are an important part of the professional environment since they show not only your skill but also your philosophy and work ethic.
I've left some comments that will help you improve your app. You are completely free to either follow them or not.
    
Cheers and Happy coding!👏👏👏
    
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
    Please, remember to tag me in your question so I can receive the notification.
    
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 22:07 UTC, merged